### ISSUE TITLE
Error while reading manifest.json: Invalid value(s) specified for validDomains[0]: "https://xyz.azurewebsites.net"

### ISSUE THREAD

**Issue by janlange** [OfficeDev/microsoft-teams-faqplusplus-app#84]
When trying to install my experts package to Teams I get this error:
Error while reading manifest.json: Invalid value(s) specified for validDomains[0]: "https://xyz.azurewebsites.net"
(I have replaced my own [BaseResourceName] with xyz in this post)

**Comment by jsuddsjr** [comment]
You don't need to specify the "https://" part.

**Comment by SebastianSchuetze** [comment]
This is correct @jsuddsjr . Had the same problem and fixed it without the https.
@janlange maybe you can close your own issue. I am 100% confident that this was the problem.

**Comment by toddanglin** [comment]
For future Google searchers, it seems the URL is now expected to have `https://` explicitly included in the manifest. If you remove the `https://` you now get this error when trying to load an extension in Teams: `Error while reading manifest.json: "validDomains[0]" is required Url should start with "https://"`
